config/routes.rb
ClassPortal::Application.routes.draw do
  resources :messages
  resources :user_histories
  resources :grades
  resources :admins
  resources :courses, :collection => {:requestEnrollment => :post}

  
  root 'static_pages#home'
  get 'sessions/new'
  get "static_pages/home"
  get "static_pages/admin"
  get "static_pages/instructor"
  get "static_pages/student"
  get "students/new"
  get "admins/new"
  get "super_admins/new"
  get "courses/new"
  get "courses/view"
  get "courses/edit"
  get 'viewCourse' => 'courses#view'
  
  
  
  
  
  
  get "/viewSelectCourse/:title/:number" => "courses#viewSelectCourse"
  post "/viewSelectCourse/:title/:number" => "courses#viewSelectCourse"
  
  
  get 'searchCourse' => 'courses#searchCourse'
  
  get 'editCourse' => 'courses#edit'
  get 'enrollCourse/:id/enroll' => 'courses#enroll'
  post 'enrollCourse/:id/enroll' => 'courses#enroll'
 
  get "student_courses/viewHistory"
  get '/viewHistory/:id' => 'student_courses#viewHistory'
  post '/viewHistory/:id' => 'student_courses#viewHistory'
  
 
  get "students/view"
  get 'viewStudent' => 'students#view' 
 
  resources :courses do
  member do
    get 'enroll'
  end
end
  get 'addInst' =>'users#newInstructor'
  post 'createInstructor' =>'users#createInstructor'
  get 'editInst' => 'instructors#edit'
  get 'signup'  => 'students#new'
  get 'edit' => 'users#edit'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get "/courses/:course_id/grades" => 'student_courses#grades'
  get "/courses/:course_id/requestEnrollment" => 'courses#requestEnrollment'
  get "/grades/new" => "student_courses#newGrade"
  post "/grades/new" => "student_courses#createGrade"
  
  get "/enrollmentRequests" => "student_courses#showEnrollmentRequests"
  get "/enrollmentRequests/courses/:course_id/students/:student_id/approve" => "student_courses#approveRequest"
  get "/enrollmentRequests/courses/:course_id/students/:student_id/deny" => "student_courses#denyRequest"

  
  get "/courses/:course_id/students" => "courses#students"
  get "/student_courses/:student_course_id/edit" => "grades#edit"
  
  get "/users/:user_id/history" => "user_histories#for_user"
  get "/courses/:course_id/drop" => "courses#dropStudent"
  get "/courses/:course_id/students/:student_id/drop" => "courses#drop"
  get "/courses/:course_id/requestInactive" => "courses#requestInactive"

  resources :users
  resources :students
  resources :instructors
  resources :super_admins
  resources :student_courses







  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if logged_in?
      if current_user.type == "Admin" || current_user.type == "SuperAdmin"
        redirect_to static_pages_admin_url
      elsif current_user.type == "Instructor"
        redirect_to static_pages_instructor_url
      elsif current_user.type == "Student"
        redirect_to static_pages_student_url
      end
    end
  end
  def admin
    if !logged_in? || (current_user.type == "Admin" && !current_user.type == "SuperAdmin")
      redirect_to static_pages_home_url
    end
  end
  
  def instructor
    if !logged_in? || !current_user.type == "Instructor"
      redirect_to static_pages_home_url
    end
  end
  
  def student
    if !logged_in? || !current_user.type == "Student"
      redirect_to static_pages_home_url
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/admin.html.erb
<% provide(:title, "Admin Home") %>

<h1>Admin Home</h1>
<p class="big_size">

<p>
  Select what you would like to do below.
</p>

<p><%= link_to "Add Admin", new_admin_path, class: "btn btn-lg btn-primary" %></p>
<p><%= link_to "Add Instructor", new_instructor_path, class: "btn btn-lg btn-primary" %></p>
<p><%= link_to "Add Student", new_student_path, class: "btn btn-lg btn-primary" %></p>
<p><%= link_to "Add Course", new_course_path, class: "btn btn-lg btn-primary" %></p>
<br />

<p><%= link_to "View Courses", courses_url, class: "btn btn-lg btn-primary" %></p>
<p><%= link_to "View Admins", admins_url, class: "btn btn-lg btn-primary" %></p>
<p><%= link_to "View Instructors", instructors_url, class: "btn btn-lg btn-primary" %></p>
<p><%= link_to "View Students", students_url, class: "btn btn-lg btn-primary" %></p>
<br />

<p><%= link_to "View all grades", grades_url, class: "btn btn-lg btn-primary" %></p>
<p><%= link_to "View enrollment requests", '/enrollmentRequests', class: "btn btn-lg btn-primary" %></p>
<p><%= link_to "View course history", user_histories_url, class: "btn btn-lg btn-primary" %></p>

app/views/static_pages/contact.html.erb
<!--Contact for anything wrong with logging in-->

<head>
    <title>Contact Us</title>
</head>

<body>
    <h1>
        Class Portal Team
    </h1>
</body>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="jumbotron">
<h1>Class Portal Home</h1>
</div>
<p>
  Welcome to the <b>Class Portal</b>! If you have an account, please login. Otherwise, sign up for one!
</p>
<p align="center"><%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %> <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %></p>
</div>

app/views/static_pages/instructor.html.erb
<% provide(:title, "Instructor Home") %>
<h1>Instructor Home</h1>
<p>
  This is the instructor home page for the <b>Class Portal</b> application.
</p>

<p><%= link_to "View Courses", courses_url, class: "btn btn-lg btn-primary" %></p>
<p><%= link_to "Edit Profile", current_user, class: "btn btn-lg btn-primary" %></p>

<p><%= link_to "View enrollment requests", '/enrollmentRequests', class: "btn btn-lg btn-primary" %></p>
<p><%= link_to "View course history", "/users/#{current_user.id}/history", class: "btn btn-lg btn-primary" %></p>

<p><%= link_to "Messages", new_message_path, class: "btn btn-lg btn-primary" %></p>

app/views/static_pages/student.html.erb
<% provide(:title, "Student Home") %>
<h1>Student Home</h1>
<p>
  This is the student home page for the <b>Class Portal</b> application.
</p>

<p><%= link_to "Search Courses", searchCourse_path, class: "btn btn-lg btn-primary" %></p>
<p><%= link_to "View Courses", courses_path, class: "btn btn-lg btn-primary" %></p>
<p><%= link_to "View Course History", "/users/#{current_user.id}/history", class: "btn btn-lg btn-primary" %></p>       
<p><%= link_to "View your grades", grades_url, class: "btn btn-lg btn-primary" %></p>


<p><%= link_to "Messages", new_message_path, class: "btn btn-lg btn-primary" %></p>