config/routes.rb
ClassPortal::Application.routes.draw do
  resources :messages
  resources :user_histories
  resources :grades
  resources :admins
  resources :courses, :collection => {:requestEnrollment => :post}

  
  root 'static_pages#home'
  get 'sessions/new'
  get "static_pages/home"
  get "static_pages/admin"
  get "static_pages/instructor"
  get "static_pages/student"
  get "students/new"
  get "admins/new"
  get "super_admins/new"
  get "courses/new"
  get "courses/view"
  get "courses/edit"
  get 'viewCourse' => 'courses#view'
  
  
  
  
  
  
  get "/viewSelectCourse/:title/:number" => "courses#viewSelectCourse"
  post "/viewSelectCourse/:title/:number" => "courses#viewSelectCourse"
  
  
  get 'searchCourse' => 'courses#searchCourse'
  
  get 'editCourse' => 'courses#edit'
  get 'enrollCourse/:id/enroll' => 'courses#enroll'
  post 'enrollCourse/:id/enroll' => 'courses#enroll'
 
  get "student_courses/viewHistory"
  get '/viewHistory/:id' => 'student_courses#viewHistory'
  post '/viewHistory/:id' => 'student_courses#viewHistory'
  
 
  get "students/view"
  get 'viewStudent' => 'students#view' 
 
  resources :courses do
  member do
    get 'enroll'
  end
end
  get 'addInst' =>'users#newInstructor'
  post 'createInstructor' =>'users#createInstructor'
  get 'editInst' => 'instructors#edit'
  get 'signup'  => 'students#new'
  get 'edit' => 'users#edit'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get "/courses/:course_id/grades" => 'student_courses#grades'
  get "/courses/:course_id/requestEnrollment" => 'courses#requestEnrollment'
  get "/grades/new" => "student_courses#newGrade"
  post "/grades/new" => "student_courses#createGrade"
  
  get "/enrollmentRequests" => "student_courses#showEnrollmentRequests"
  get "/enrollmentRequests/courses/:course_id/students/:student_id/approve" => "student_courses#approveRequest"
  get "/enrollmentRequests/courses/:course_id/students/:student_id/deny" => "student_courses#denyRequest"

  
  get "/courses/:course_id/students" => "courses#students"
  get "/student_courses/:student_course_id/edit" => "grades#edit"
  
  get "/users/:user_id/history" => "user_histories#for_user"
  get "/courses/:course_id/drop" => "courses#dropStudent"
  get "/courses/:course_id/students/:student_id/drop" => "courses#drop"
  get "/courses/:course_id/requestInactive" => "courses#requestInactive"

  resources :users
  resources :students
  resources :instructors
  resources :super_admins
  resources :student_courses







  

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
      @message.update_attributes(:sender_id => current_user.id )        
        format.html { redirect_to new_message_path, notice: 'Message was successfully created.' }
        format.json { render action: 'new', status: :created, location: @message }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
          params.require(:message).permit(:content, :sender_id, :receiver_id) 
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= form_for @message do |f| %>

 <% if current_user.type == "Instructor" %>
       
  <div class="field" >
    <%= f.label :name, 'Student' %><br>
    <%= collection_select(:message, :receiver_id, Student.all, :id, :name) %>
  </div>
  <%end%>
  
  <% if current_user.type == "Student" %>
       
  <div class="field" >
    <%= f.label :name, 'Instructor' %><br>
    <%= collection_select(:message, :receiver_id, Instructor.all, :id, :name) %>
  </div>
  <%end%>
  
  
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  
    <%= f.submit "Send" %>
 <% end %>



<h1>Received Messages</h1>


<table class="table table-striped">
    <thead>
      <tr>
        <th>Sender</th>
        <th></th>
        
        <th>Content</th>
        </tr>
    </thead>
    
    <% @message = Message.where("receiver_id = ?", current_user.id ) %>
   
     <% @message.each do |m|%>
    <tbody>
      <tr>
              <%@user = User.find(m.sender_id) %>  
         <th><%= @user.name %></th>
        <th></th>
        
         <th><%= m.content %></th>
         </tr>
     </tbody>
            
    <% end %>
    
</table>

app/views/messages/show.html.erb
<h1>YEY</h1>
<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>